apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: g6o3xj4gw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: g6o3xj4gw-nodejs 
  name: g6o3xj4gw-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: g6o3xj4gw-nodejs 
